### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by caosdp-rs** [marquin-dev/youtubeVideoDownloader#1]

**Comment by devmarquinhos** [comment]
Oi! Eu usei a biblioteca do pyinstaller. 

`pyinstaller .\index.py --onefile -n YoutubeDownloader`

Este foi o comando que usei para gerar o executável, o `--onefile` para gerar um arquivo só e o `-n YoutubeDownloader` para gerar já com o nome de YoutubeDownloader. Espero que tenha ajudado!
